development:
  adapter: postgresql
  database: guitarlab_dev
  encoding: utf8
  template: template0
  host: localhost

test:
    adapter: postgresql
    database: guitarlab_test
    encoding: utf8
    template: template0
    host: localhost
